on:
  workflow_dispatch:  # This allows you to manually trigger the workflow
  push:
    branches:
      - main  # Runs on push, but you can remove this line to disable auto-run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
